Adapt /sbin/usb for M vold changes, assume first public partition is always SDcard

diff --git a/ik.ramdisk/common/sbin/usb b/ik.ramdisk/common/sbin/usb
--- a/ik.ramdisk/common/sbin/usb
+++ b/ik.ramdisk/common/sbin/usb
@@ -4,7 +4,8 @@ VERSION=1.3
 
 LUN=/sys/devices/msm_dwc3/f9200000.dwc3/gadget/lun0
 SDCARD=/dev/block/mmcblk1
-SDMOUNT="$(ls -1d /storage/* | grep '\/....-....$')"
+SDMOUNT="$(ls -1 /dev/block/vold | grep -m1 '^public\:')"
+[ -n "$SDMOUNT" ] && HAS_SDCARD=true || HAS_SDCARD=false
 SD_MOUNTED=false
 USB_MODE=false
 ADB_ON=false
@@ -40,7 +41,11 @@ CHECK_SU() {
 }
 
 CHECK_SD_MOUNTED() {
-	mountpoint -q $SDMOUNT && SD_MOUNTED=true || SD_MOUNTED=false
+	$HAS_SDCARD && {
+		[ -n "$(grep $SDMOUNT /proc/mounts)" ] && SD_MOUNTED=true || SD_MOUNTED=false
+	} || {
+		SD_MOUNTED=false
+	}
 }
 
 CHECK_ADB_ON() {
@@ -101,11 +106,15 @@ DISPLAY_STATUS() {
 	} || {
 		echo "USB 2.0 HighSpeed"
 	}
-	CHECK_SD_MOUNTED
-	$SD_MOUNTED && {
-		echo "SDcard is currently mounted in Android."
+	$HAS_SDCARD && {
+		CHECK_SD_MOUNTED
+		$SD_MOUNTED && {
+			echo "SDcard is currently mounted in Android."
+		} || {
+			echo "SDcard is not mounted in Android."
+		}
 	} || {
-		echo "SDcard is not mounted in Android."
+		echo "Unable to find an SDcard in your phone."
 	}
 }
 
@@ -202,6 +211,7 @@ UNMOUNT_SDCARD() {
 }
 
 ASK_MOUNT_SDCARD() {
+	$HAS_SDCARD || return
 	CHECK_SD_MOUNTED
 	$SD_MOUNTED && return
 	echo -n "Mount SDcard in Android? (y/n): "
@@ -338,9 +348,14 @@ ums)
 	CHECK_SU
 	case $2 in
 	1|on|start|enable)
-		CHECK_USB_30 $3
-		UMS_ON
-		echo "Done. PLEASE USE EJECT MEDIA ON PC BEFORE TURNING OFF UMS!"
+		$HAS_SDCARD && {
+			CHECK_USB_30 $3
+			UMS_ON
+			echo "Done. PLEASE USE EJECT MEDIA ON PC BEFORE TURNING OFF UMS!"
+		} || {
+			echo "Error: Unable to find an SDcard in your phone!" 1>&2
+			exit 1
+		}
 		;;
 	0|off|stop|disable)
 		ASK_SD_MOUNT=true
