Check for SDcard existence in /sbin/usb

diff --git a/ik.ramdisk/common/sbin/usb b/ik.ramdisk/common/sbin/usb
--- a/ik.ramdisk/common/sbin/usb
+++ b/ik.ramdisk/common/sbin/usb
@@ -1,10 +1,11 @@
 #!/system/bin/sh
 
-VERSION=1.3
+VERSION=1.4
 
 LUN=/sys/devices/msm_dwc3/f9200000.dwc3/gadget/lun0
 SDCARD=/dev/block/mmcblk1
 SDMOUNT=/storage/extSdCard
+[ -b "$SDCARD" ] && HAS_SDCARD=true || HAS_SDCARD=false
 SD_MOUNTED=false
 USB_MODE=false
 ADB_ON=false
@@ -40,7 +41,11 @@ CHECK_SU() {
 }
 
 CHECK_SD_MOUNTED() {
-	mountpoint -q $SDMOUNT && SD_MOUNTED=true || SD_MOUNTED=false
+	$HAS_SDCARD && {
+		mountpoint -q $SDMOUNT && SD_MOUNTED=true || SD_MOUNTED=false
+	} || {
+		SD_MOUNTED=false
+	}
 }
 
 CHECK_ADB_ON() {
@@ -101,11 +106,15 @@ DISPLAY_STATUS() {
 	} || {
 		echo "USB 2.0 HighSpeed"
 	}
-	CHECK_SD_MOUNTED
-	$SD_MOUNTED && {
-		echo "SDcard is currently mounted in Android."
+	$HAS_SDCARD && {
+		CHECK_SD_MOUNTED
+		$SD_MOUNTED && {
+			echo "SDcard is currently mounted in Android."
+		} || {
+			echo "SDcard is not mounted in Android."
+		}
 	} || {
-		echo "SDcard is not mounted in Android."
+		echo "Unable to find an SDcard in your phone."
 	}
 }
 
@@ -202,6 +211,7 @@ UNMOUNT_SDCARD() {
 }
 
 ASK_MOUNT_SDCARD() {
+	$HAS_SDCARD || return
 	CHECK_SD_MOUNTED
 	$SD_MOUNTED && return
 	echo -n "Mount SDcard in Android? (y/n): "
@@ -284,6 +294,7 @@ CHECK_USB_30() {
 			USE_USB_30=true
 		} || {
 			echo "Error: USB 3.0 SuperSpeed support not available on host!" 1>&2
+			echo "Ensure your device is plugged into a USB 3.0 slot using a USB 3.0 cable first."
 			echo -n "Continue anyway (y/n)? "
 			read CONT
 			case "$CONT" in
@@ -338,9 +349,14 @@ ums)
 	CHECK_SU
 	case $2 in
 	1|on|start|enable)
-		CHECK_USB_30 $3
-		UMS_ON
-		echo "Done. PLEASE USE EJECT MEDIA ON PC BEFORE TURNING OFF UMS!"
+		$HAS_SDCARD && {
+			CHECK_USB_30 $3
+			UMS_ON
+			echo "Done. PLEASE USE EJECT MEDIA ON PC BEFORE TURNING OFF UMS!"
+		} || {
+			echo "Error: Unable to find an SDcard in your phone!" 1>&2
+			exit 1
+		}
 		;;
 	0|off|stop|disable)
 		ASK_SD_MOUNT=true
